### ISSUE TITLE
Marshalling Issue on Int

### ISSUE THREAD

**Issue by cancellin** [ffissore/jrecordbind#13]
Hi,

First let me say that i am very fan of JrecordBind and i 'm sorry to say that I found a Bug ( i think).

**Description:**

_for this element :_
```
<xs:element name="endPage" type="PageTypeOPT" jrb:length="3" jrb:padder="org.fissore.jrecordbind.padders.ZeroLeftPadder"/>
    <xs:simpleType name="PageTypeOPT">
        <xs:restriction base="xs:int">
            <xs:pattern value="(0)|(9)|(19)|(500)"/>
        </xs:restriction>
    </xs:simpleType>
```

"009" will be unmarshalled to 9 and then will be marshalled backt to "9  " instead of "009"

**For information,**

if element is of type int , it works perfectly
```
<xs:element name="endPage" type="xs:int" jrb:length="3" jrb:padder="org.fissore.jrecordbind.padders.ZeroLeftPadder"/>
```

if element is of a simple type of string , it works perfectly

```<xs:element name="endPage" type="PageTypeOPT" jrb:length="3" jrb:padder="org.fissore.jrecordbind.padders.ZeroLeftPadder"/>
    <xs:simpleType name="PageTypeOPT">
        <xs:restriction base="xs:string">
            <xs:pattern value="(000)|(009)|(019)|(500)"/>
        </xs:restriction>
    </xs:simpleType>
```
Thanks in advance. If you need more information , let me know.
Regards

**PS:**
I do provide a zip file containing a .xsd file, a file to unmarshall and the failed marshalled file.
[resources.zip](https://github.com/ffissore/jrecordbind/files/9040740/resources.zip)

**Comment by ffissore** [comment]
Hi. Version 3.3.0 has been released and it should soon be available on maven central
It includes support for padders and converters on `simpleType` elements

Please bear in mind that restrictions (as in your example) are not supported yet. I hope I'll be able to support them soon, but it's not a small effort.

**Comment by cancellin** [comment]
Hi,

Thanks a lot. I 'll try it as soon as possible.

I have to say that you read my mind. I'm indeed interested for restrictions support :)

I do have a workaround (but it doesn't satisfy me ) . After unmarshalling the file, i create an xml output with JrecordBind and validate it against the .xsd (same used by JrecordBind) with Jackson lib. 

Sorry for the late answer but your mails went directly to my junk .

Regards
