### ISSUE TITLE
URL with XSD gives 404 NOT FOUND error.

### ISSUE THREAD

**Issue by roizpi** [ffissore/jrecordbind#4]
I am maintaining an old project using `jrecordbin`, but the URL https://java.net/projects/jrecordbind/2/xsd gives 404 `NOT FOUND` error. So my project is giving multiple errors in chain, and I guess this is the reason. Is there a new link for its xmlns definition?, or isn't this library supported anymore?

 Thank you,
  Rodrigo Izquierdo.

**Comment by ffissore** [comment]
That xsd has never been published: the url was used to namespace the jrb attributes. What's the error message you're getting?

**Comment by roizpi** [comment]
I get this error on build.xml:
*Failed to load type(s): Class not found org.jvnet.jaxb2_commons.xjc.XJC2Task*

When running ant on command line:
*build.xml:47: grammar is not specified*

Line 47:
`<target name="regenerate-beans" depends="init">
		<taskdef name="xjc2" classname="org.jvnet.jaxb2_commons.xjc.XJC2Task">
			<classpath refid="jrb.compile.classpath" />
		</taskdef>
<xjc2.....
</xjc2>
</target>`

**Comment by roizpi** [comment]
I've solved the problem, IntelliJ underlines `<taskdef` as error, as if saying it hasn't found necessary dependencies.

In summing up, "grammar is not specified" error meant the file defined within the `xjc2` block didn't exist.

Also Intellij still colours the URL `xmlns:jrb="http://jrecordbind.dev.java.net/2/xsd"):`. in red, and it is kind of confusing, as I was taught to remove all errors before commiting any project.

So this is solved and was not related to jrecordbind at all. Thank you for your prompt answer @ffissore .

**Comment by ffissore** [comment]
Glad you solved it @roizpi Thank you for your feedback!
